### PR TITLE
Proofread ch03-01

### PR DESCRIPTION
**Pull request by joeljpresent**
I have proofread Chapter 03-01.

### CODE REVIEW

**Comment by Jimskapt** [comment]
Hi Joel, thank you so much for your great proofreading !

(I think I have to correct all my non-breaking spaces from U+2009 to U+0020 in all next already translated chapters, means until ch07, except ch05)

**Comment by joeljpresent** [comment]
Note that is the no-break space is U+00A0 (U+0020 is regular space).
I will try to make a script that will convert whitespace to non-breaking space when needed.

**Comment by Jimskapt** [comment]
Yeah, i've learn the differencies between U+00A0 and U+0020 after commenting, I've updated it after ;-)

The script is a nice idea, maybe we could do something together with my new tool [Castor Whispers](https://github.com/Jimskapt/castor_whispers)

**Comment by joeljpresent** [comment]
This script should work fine:

``` rust
use regex::Regex;

fn main() {
	let args: Vec<String> = std::env::args().collect();

	if args.len() < 1 {
		panic!("Please specify the path to your input file");
	}

	let input_path = args[1].as_str();

	let file_contents = std::fs::read_to_string(input_path)
        .expect("Could not read file");
    
    let regex = Regex::new(r"\s([;:!?])").unwrap();
    let new_content = regex.replace_all(&file_contents, "\u{A0}$1");

    println!("{}", new_content);
}
```

We could create a `/FRENCH/tools` folder similar to the `/tools/` folder of the repo.

**Pull request merged**
